api/urls.py
from django.urls import path

from api import views

app_name = "api"


urlpatterns = [
    path('', views.APIView.as_view(), name="api_list"),

    path('list/task/', views.ListTaskAPIView.as_view(), name="list_task_api"),
    path('list/task-ids/', views.ListTaskidsAPIView.as_view(), name="list_task_ids_api"),

    path('list/task-ids-titles/', views.ListTaskidstitlesAPIView.as_view(), name="list_task_ids_titles_api"),
    path('list/pending/task-ids-titles/', views.ListPendingTaskidstitlesAPIView.as_view(), name="list_pending_task_ids_titles_api"),
    path('list/resolved/task-ids-titles/', views.ListResolvedTaskidstitlesAPIView.as_view(), name="list_resolved_task_ids_titles_api"),

    path('list/task-ids-user/', views.ListTaskidsuserAPIView.as_view(), name="list_task_ids_user_api"),
    path('list/pending/task-ids-user/', views.ListPendingTaskidsuserAPIView.as_view(), name="list_pending_task_ids_user_api"),
    path('list/resolved/task-ids-user/', views.ListResolvedTaskidsuserAPIView.as_view(), name="list_resolved_task_ids_user_api"),

    path('detail/task/<int:pk>/', views.DetailTaskAPIView.as_view(), name="detail_task_api"),
    path('create/task/', views.CreateTaskAPIView.as_view(), name="create_task_api"),
    path('update/task/<int:pk>/', views.UpdateTaskAPIView.as_view(), name="update_task_api"),
    path('delete/task/<int:pk>/', views.DeleteTaskAPIView.as_view(), name="delete_task_api"),
]

examen2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include("todo.urls")),
    path('api/', include("api.urls")),
]

todo/urls.py
from django.urls import path

from todo import views

app_name = 'todo'

urlpatterns = [
    ## TASK URLS ##
    path('list/task/', views.ListTask.as_view(), name="list_task"),
    path('new/task/', views.CreateTask.as_view(), name="create_task"),
    path('detail/task/<int:pk>/', views.DetailTask.as_view(), name="detail_task"),
    path('update/task/<int:pk>/', views.UpdateTask.as_view(), name="update_task"),
    path('delete/task/<int:pk>/', views.DeleteTask.as_view(), name="delete_task"),
]

todo/models.py
from django.db import models
from django.contrib.auth.models import User


STATE_OPTIONS = (
    ("PENDING", "PE"),
    ("RESOLVED", "RE")
)


class Task(models.Model):
    title = models.CharField(max_length=50, default="Task title")
    description = models.CharField(max_length=200, default="Task description")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp =  models.DateTimeField(auto_now_add=True)
    state = models.CharField(max_length=16, choices=STATE_OPTIONS)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.title
    

todo/forms.py
from django import forms
from .models import Task


class NewTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = [
            "title",
            "description",
            "user",
            "state",
            "status",
        ]
        widgets = {
            "title": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Write the task title"}),
            "description": forms.Textarea(attrs={"rows": 4, "type": "text", "class": "form-control", "placeholder": "Description of the task"}),
            "user": forms.Select(attrs={"type": "select", "class": "form-control"}),
            "state": forms.Select(attrs={"type": "select", "class": "form-control"}),
            "status": forms.CheckboxInput(attrs={"type": "checkbox"}),
        }

class UpdateTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = [
            "title",
            "description",
            "user",
            "state",
            "status",
        ]
        widgets = {
            "title": forms.TextInput(attrs={"type": "text", "class": "form-control", "placeholder": "Write the task title"}),
            "description": forms.Textarea(attrs={"rows": 4, "type": "text", "class": "form-control", "placeholder": "Description of the task"}),
            "user": forms.Select(attrs={"type": "select", "class": "form-control"}),
            "state": forms.Select(attrs={"type": "select", "class": "form-control"}),
            "status": forms.CheckboxInput(attrs={"type": "checkbox"}),
        }

todo/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy

from .models import Task
from .forms import NewTaskForm, UpdateTaskForm

# # # # CRUD TASK # # # #

## CREATE ## 
class CreateTask(generic.CreateView):
    template_name = 'todo/create_task.html'
    model = Task
    form_class = NewTaskForm
    success_url = reverse_lazy("todo:list_task")

## LIST ##
class ListTask(generic.View):
    template_name = 'todo/list_task.html'
    context = {}

    def get(self, request):
        self.context = {
            'tasks': Task.objects.filter(status=True)
        }
        return render(request, self.template_name, self.context)

## DETAIL ##
class DetailTask(generic.View):
    template_name = 'todo/detail_task.html'
    context = {}

    def get(self, request, pk):
        self.context = {
            'tasks': Task.objects.get(pk=pk)
        }
        return render(request, self.template_name, self.context)
    
## UPDATE ## 
class UpdateTask(generic.UpdateView):
    template_name = 'todo/update_task.html'
    model =Task
    form_class = UpdateTaskForm
    success_url = reverse_lazy("todo:list_task")

## DELETE ## 
class DeleteTask(generic.DeleteView):
    template_name = 'todo/delete_task.html'
    model = Task
    success_url = reverse_lazy("todo:list_task")

templates/todo/create_task.html
{% extends "base/base.html" %}

{% block title %}NEW TASK{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <button style="margin: 2%;" type="submit" class="btn btn-outline-success form-control">New Task</button>
            <br>
            <a href="{% url 'todo:list_task' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}

templates/todo/delete_task.html
{% extends "base/base.html" %}

{% block title %}DELETE TASK{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            <h3>DELETE TASK CONFITMATION: "{{ object }}"?</h3>
            
            <button type="submit" class="btn btn-outline-danger">Delete task</button>
            <a href="{% url 'core:list_gg' %}" class="btn btn-outline-warning">Cancel</a>
    </form>
{% endblock content %}

templates/todo/list_task.html
{% extends "base/base.html" %}

{% block title %}LIST TASK{% endblock title %}

{% block content %}
    <a href="{% url 'todo:create_task' %}" class="btn btn-outline-success form-control">New task</a>
    <table class="table table-striped">
        <thead>
            <th>ID</th>
            <th>TITLE</th>
            <th>USER</th>
            <th>TIMESTAMP</th>
            <th>STATE</th>
            <th></th>
            <th>ACTIONS</th>
            <th></th>
        </thead>
        <tbody>
            {% for tk in tasks %}
                <tr>
                    <td>{{ tk.id }}</td>
                    <td>{{ tk.title }}</td>
                    <td>{{ tk.user }}</td>
                    <td>{{ tk.timestamp }}</td>
                    <td>{{ tk.state }}</td>
                    <td><a href="{% url 'todo:detail_task' tk.pk %}" class="btn btn-outline-info">Detail</a></td>
                    <td><a href="{% url 'todo:update_task' tk.pk %}" class="btn btn-outline-warning">Update</a></td>
                    <td><a href="{% url 'todo:delete_task' tk.pk %}" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}
    

templates/todo/update_task.html
{% extends "base/base.html" %}

{% block title %}UPDATE TASK{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form }}
            <button style="margin: 2%;" type="submit" class="btn btn-outline-success form-control">New Task</button>
            <br>
            <a href="{% url 'todo:list_task' %}" class="btn btn-outline-warning form-control">Cancel</a>
    </form>
{% endblock content %}